top:
  inept:
    datasource:
      ddl-auto: validate
      host: 127.0.0.1
      port: 5432
      database: inept_blog
      username: user
      password: 123456
    server:
      port: 8080
    jwt:
      issuer: boot4-rbac
      access-secret-key: U7lIBboDJW24Ak1ROncsOyuVNuugnZriJWZBY9ULB//4EdZU5AeGCRlVAdXMKxinBynktrcuQgGVCM4Fm54tBg==     #openssl rand -base64 64
      refresh-secret-key: mOxd0bfTmeEsf8kkmFldk/ztkys6FkKRSGF0r66n6coKPRvqm0xJ9tCOBunH0v/9GaWqop0ZIgsEMUNyIZqPTA==    #openssl rand -base64 64
      access-expires-minutes: 15
      refresh-expires-minutes: 10080  #7day
